# Generated by Django 5.0 on 2024-02-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_todolist_remove_product_brand_item_delete_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catagory_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_description", models.CharField(max_length=200)),
                ("product_on_cart", models.BooleanField()),
                (
                    "product_catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.catagory"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ToDoList",
        ),
    ]
