# Generated by Django 5.0 on 2024-02-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0004_catagory_product_delete_item_delete_todolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meat_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meat_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_catagory",
        ),
        migrations.CreateModel(
            name="Cuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.CharField(max_length=1000)),
                ("bone_in", models.BooleanField()),
                (
                    "cuts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.meat_type",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Catagory",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
