# Generated by Django 5.0 on 2024-08-12 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0007_fags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cuts",
        ),
        migrations.DeleteModel(
            name="Meat_type",
        ),
    ]
