# Generated by Django 5.0 on 2024-08-12 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0008_delete_cuts_delete_meat_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fags",
            old_name="swich",
            new_name="switch",
        ),
    ]
