# Generated by Django 5.0 on 2024-08-12 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0009_rename_swich_fags_switch"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fags",
        ),
    ]
