# Generated by Django 5.0 on 2024-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0010_delete_fags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fag", models.CharField(max_length=100)),
                ("switch", models.BooleanField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
