# Generated by Django 5.0 on 2024-08-19 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0011_fags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fags",
            name="fag",
        ),
        migrations.RemoveField(
            model_name="fags",
            name="price",
        ),
        migrations.RemoveField(
            model_name="fags",
            name="switch",
        ),
    ]
