# Generated by Django 5.0 on 2024-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0012_remove_fags_fag_remove_fags_price_remove_fags_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="fags",
            name="fag",
            field=models.CharField(default="Cigarette", max_length=100),
        ),
        migrations.AddField(
            model_name="fags",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fags",
            name="switch",
            field=models.BooleanField(default=False),
        ),
    ]
