# Generated by Django 5.0 on 2024-08-20 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0013_fags_fag_fags_price_fags_switch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fags",
            name="fag",
        ),
        migrations.RemoveField(
            model_name="fags",
            name="price",
        ),
        migrations.RemoveField(
            model_name="fags",
            name="switch",
        ),
    ]
