# Generated by Django 5.0 on 2024-08-21 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0015_fags_fag_fags_price_fags_switch"),
    ]

    operations = []
