# Generated by Django 5.0 on 2024-08-21 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0016_auto_20240821_1237"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fags",
        ),
    ]
