# Generated by Django 5.0 on 2024-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0017_delete_fags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fag", models.CharField(default="Cigarette", max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("switch", models.BooleanField(default=False)),
            ],
        ),
    ]
