# Generated by Django 5.0 on 2024-08-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0018_fags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Found_in",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "fags",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.fags"
                    ),
                ),
            ],
        ),
    ]
