# Generated by Django 5.0 on 2024-08-23 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0019_found_in"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Found_in",
            new_name="Found",
        ),
    ]
