# Generated by Django 5.0 on 2024-08-23 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0020_rename_found_in_found"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Found",
            new_name="Found_in",
        ),
    ]
